// Code generated by xgo (XGo); DO NOT EDIT.

package foo

const _ = true

type StructFoo struct {
	Value int
}
type IntFoo int
//line internal/goxls/testdata/foo/foo.gop:10:1
func Foo() {
//line internal/goxls/testdata/foo/foo.gop:11:1
	var err error
//line internal/goxls/testdata/foo/foo.gop:12:1
	err.Error()
}
//line internal/goxls/testdata/foo/foo.gop:15:1
func _() {
//line internal/goxls/testdata/foo/foo.gop:16:1
	var sFoo StructFoo
//line internal/goxls/testdata/foo/foo.gop:17:1
	if
//line internal/goxls/testdata/foo/foo.gop:17:1
	x := sFoo; x.Value == 1 {
//line internal/goxls/testdata/foo/foo.gop:18:1
		return
	}
}
//line internal/goxls/testdata/foo/foo.gop:22:1
func _() {
//line internal/goxls/testdata/foo/foo.gop:23:1
	shadowed := 123
//line internal/goxls/testdata/foo/foo.gop:26:1
	{
//line internal/goxls/testdata/foo/foo.gop:25:1
		shadowed := "hi"
//line internal/goxls/testdata/foo/foo.gop:26:1
		_ = shadowed
	}
//line internal/goxls/testdata/foo/foo.gop:28:1
	_ = shadowed
}
