// Code generated by xgo (XGo); DO NOT EDIT.

package codelens

import "testing"
//line internal/goxls/testdata/codelens/codelens_test.gop:5:1
func TestMain(m *testing.M) {
}
//line internal/goxls/testdata/codelens/codelens_test.gop:7:1
func TestFuncWithCodeLens(t *testing.T) {
}
//line internal/goxls/testdata/codelens/codelens_test.gop:10:1
func thisShouldNotHaveACodeLens(t *testing.T) {
}
//line internal/goxls/testdata/codelens/codelens_test.gop:13:1
func BenchmarkFuncWithCodeLens(b *testing.B) {
}
//line internal/goxls/testdata/codelens/codelens_test.gop:16:1
func helper() {
}
