// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "fmt"

const _ = true
//line internal/goxls/testdata/codelens_main/main.gop:3:1
func helper() {
}
//line internal/goxls/testdata/codelens_main/main.gop:5
func main() {
//line internal/goxls/testdata/codelens_main/main.gop:5:1
	fmt.Println("run")
}
