# This workflow will build a Go project

name: Go

on:
  push:
    branches: [ "goplus" ]
  pull_request:
    branches: [ "goplus" ]

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x, 1.22.x, 1.23.x, 1.24.x, 1.25.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        cache-dependency-path: go.sum

    - name: Set up XGo
      uses: goplus/setup-xgo@v1
      with:
        xgo-version: 1.5.x

    - name: Build Go+ tools
      run: |
        cd gop
        go build -v ./...

    - name: Test Go+ tools
      run: |
        cd gop
        go test -v -coverprofile="coverage.txt" -covermode=atomic ./...

    - name: Build Goxls
      run: |
        cd gopls
        go build -v ./...

    - name: Test Goxls
      run: |
        cd gopls
        go test -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./gop/coverage.txt
