// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "fmt"

const _ = true

var myString string
//line internal/goxls/testdata/lambda/lambda.gop:3:1
func onStart(fn func(int) int) {
//line internal/goxls/testdata/lambda/lambda.gop:4:1
	fmt.Println(fn(100), myString)
}
//line internal/goxls/testdata/lambda/lambda.gop:7
func main() {
//line internal/goxls/testdata/lambda/lambda.gop:7:1
	onStart(func(xparam int) int {
//line internal/goxls/testdata/lambda/lambda.gop:8:1
		return xparam * xparam
	})
//line internal/goxls/testdata/lambda/lambda.gop:11:1
	onStart(func(yparam int) int {
//line internal/goxls/testdata/lambda/lambda.gop:11:1
		return yparam
	})
}
